Analiza podatkov

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv(r"zajete_macke.csv")
df.head()

,ime,na voljo,lokacija,starost,spol,pasma,posvojitev v paru,velikost,živi z otroki
0,Socks,available,Cornwall,52,Male,Domestic Shorthair,ne,Medium,da
1,Teddy,available,Cornwall,184,Male,Russian White,ne,Medium,ne
2,Ryobi,available,Berkshire,2,Female,NaN,ne,NaN,da
3,Stanley,available,Berkshire,2,Male,NaN,ne,NaN,da
4,Ivy,available,Hertfordshire,50,Female,Domestic Shorthair,ne,NaN,NaN

Analiza mačk

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ime                37 non-null     str
 1   na voljo           37 non-null     str
 2   lokacija           37 non-null     str
 3   starost            37 non-null     int64
 4   spol               35 non-null     str
 5   pasma              32 non-null     str
 6   posvojitev v paru  37 non-null     str
 7   velikost           15 non-null     str
 8   živi z otroki      22 non-null     str
dtypes: int64(1), str(8)
memory usage: 2.7 KB

In [11]:
df.isnull().sum()

ime                   0
na voljo              0
lokacija              0
starost               0
spol                  2
pasma                 5
posvojitev v paru     0
velikost             22
živi z otroki        15
dtype: int64

In [14]:
df.sort_values(by="starost", ascending= False).head(10)

,ime,na voljo,lokacija,starost,spol,pasma,posvojitev v paru,velikost,živi z otroki
1,Teddy,available,Cornwall,184,Male,Russian White,ne,Medium,ne
17,Rusty,available,Bedfordshire,162,Male,Domestic Shorthair,da,Medium,da
14,Nola,available,Hertfordshire,145,Female,Ragdoll,ne,NaN,NaN
13,Gloria,available,Hertfordshire,144,Female,Domestic Shorthair,ne,NaN,NaN
16,Nelly,available,Bedfordshire,138,Female,Domestic Shorthair,da,Medium,da
34,Mildred,reserved,Cornwall,102,Female,Domestic Shorthair,ne,Medium,da
28,Tango,reserved,Berkshire,91,Male,Domestic Shorthair,ne,NaN,da
11,Tigger,available,Cornwall,90,Male,Domestic Shorthair,da,Medium,da
36,Hobbes,reserved,Hertfordshire,80,Male,Domestic Shorthair,ne,NaN,NaN
31,Coco,reserved,Cornwall,78,Female,Domestic Shorthair,ne,Medium,da